### ISSUE TITLE
Conflict with MIA Dictionary

### ISSUE THREAD

**Issue by TowelSniffer** [pigoz/anki-canvas#10]
First of all, thank you for sharing this, its a beautiful card type. 

however, I found a bit of a weird bug this but if you have Mia Dictionary installed with this note type (https://ankiweb.net/shared/info/1655992655) the cards work fine but the moment you open the dictionary either from the main menu of by looking up a word, the cards stop displaying with the error: 

Invalid HTML on card: SecurityError: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.

This error persists until you restart Anki. I'm just wondering if this is solvable

**Comment by pigoz** [comment]
Could you test whether this fixes your issue? If possible I'd rather not install the MIA extension :)

[deck.apkg.zip](https://github.com/pigoz/anki-canvas/files/4105265/deck.apkg.zip)

**Comment by TowelSniffer** [comment]
Hi, thanks for the quick response. I'm still getting the same issue with that zip. I'm not too concerned with this either so if it's a bother, don't worry about it :)

**Comment by pigoz** [comment]
@TowelSniffer why did you close this? No longer relevant?

**Comment by TowelSniffer** [comment]
Hi, the bug still exists, but I have used a few of MIA addons and literally all of them have some kind of conflict with my javascript. I don't understand what is causing this bug and if it's fixable then cool however I kind of assumed that a fix would need to be implemented in MIA dictionary.
