### ISSUE TITLE
What about desktop Anki?

### ISSUE THREAD

**Issue by nicolasmaia** [pigoz/anki-canvas#2]
Is there a way to also draw on desktop Anki?

**Comment by pigoz** [comment]
What input device would you use to draw on desktop Anki? Mouse doesn't seem very convenient for the task.

**Comment by nicolasmaia** [comment]
You're right. There are quite a few laptop touchscreens these days, though.

**Comment by pigoz** [comment]
Fair point, I think the current widget might work as-is on desktop Anki, you just have to edit the css that hides it when not in mobile mode on the card layout preferences.

I am leaving this open since this might be a good change on my part to do for everyone.

**Comment by pigoz** [comment]
I added support for desktop Anki in version 0.3 https://github.com/pigoz/anki-canvas/releases/tag/v0.3 🚀 

It was actually a little more involved than I initially thought since Anki doesn't allow to use sessionStorage.

**Comment by nicolasmaia** [comment]
Come to think of it, it would be convenient to draw with a mouse too. Because otherwise in my current setup I'd only be able to draw on my phone, and avoid the writing cards on desktop lile the plague.

**Comment by pigoz** [comment]
I added mouse support when I closed this issue. Is that not working for you?

**Comment by nicolasmaia** [comment]
Oops, you're right. I think I was still in the old version, sorry!
