### ISSUE TITLE
Modifying brush thickness

### ISSUE THREAD

**Issue by nicolasmaia** [pigoz/anki-canvas#3]
Is there a way to make the lines thinner? If so, it would be useful to have it documented in the README.

**Comment by pigoz** [comment]
Not configurable at the moment. If you can edit code, you need to change this https://github.com/pigoz/anki-canvas/blob/master/src/front.ts#L76 to

```
rendercanvas(canvas, state, { lineWidth: 12 });
```

In a few days I will add a way to provide options in the card template, using a `script` tag, like so:

```
<script>
window.AnkiCanvasOptions = {
  frontCanvasSize: 300,
  frontLineWidth: 11,
  backCanvasSize: 150,
  backLineWidth: 12,
}
</script>
```

**Comment by pigoz** [comment]
Done, see README and https://github.com/pigoz/anki-canvas/releases/tag/v0.3 🚀
