### ISSUE TITLE
Anki night mode - line color

### ISSUE THREAD

**Issue by JhonnySalles** [pigoz/anki-canvas#5]
I use anki night mode often, is it possible to change the color of the line?  because today the only method was to add panel in the exception, which makes the night mode useless

**Comment by pigoz** [comment]
Great idea! I will add support for it. Is that for AnkiDroid or on desktop Anki with https://github.com/krassowski/Anki-Night-Mode ?

I'm thinking about exposing a theming API to the options by adding a new `colorScheme` property which will accept the values: `'light' | 'dark' | 'auto'`.  The `auto` value will be the default and will automatically change the colors of the drawing area to the dark version when night mode is activated.

**Comment by JhonnySalles** [comment]
I use more on ankidroid, however it's a good idea to leave it for the anki pc.  I use the extension on the computer too, however I did not even check to see if there is any difference, since my deck is configured to ignore the board

**Comment by JhonnySalles** [comment]
Thank you very much, because it is a very good resource that you have developed and it helps me a lot, because I do not like to activate the notes of the anki to write on the card, it hinders the scrolling of the screen.

**Comment by JhonnySalles** [comment]
If you want to add in your manual, I made a small change to make the frame size proportional to the screen. Because I use a tablet and a cell phone, it is disproportionate in one of them. Here's the code:
Add in front and back: 
<script>
    var screenSize = screen.width;
    window.AnkiCanvasOptions = {
      frontCanvasSize: screenSize - 60,
      frontLineWidth: 15,
      backCanvasSize: (screenSize - 60 ) / 2,
      backLineWidth: 3.5,
    }
  </script>
 
I only noticed that it was disproportionate in the computer, however in this case I believe that it would solve to obtain the size of the div.
But on tests I performed on my cell phone, I often ignored the size of the div for some reason I did not delve into searching.

**Comment by pigoz** [comment]
@JhonnySalles Could you try this? It's a test version with night mode support. I've only tested in AnkiDroid.

[漢字.apkg.zip](https://github.com/pigoz/anki-canvas/files/3173422/apkg.zip)

**Comment by JhonnySalles** [comment]
Of course, I will do the tests and I will inform you

**Comment by JhonnySalles** [comment]
I did some tests, in the computer the addon night mode ends up ignoring the frame and does not perform the automatic inversion like the anki droid:

![Sem título](https://user-images.githubusercontent.com/43912638/57633195-8c7cea00-7579-11e9-8e6c-efd9d0135633.jpg)

Taking the test on the ankidroid did not find any difference, because the line still remains in black color. Has a new variable been added to the line color?
Checking the deck that was shared I found no such variable.
![2019_05_13_12 13 00](https://user-images.githubusercontent.com/43912638/57633251-a61e3180-7579-11e9-8701-12839087f0cc.jpg)
![2019_05_13_12 13 07](https://user-images.githubusercontent.com/43912638/57633252-a6b6c800-7579-11e9-9d0f-e28615091fa9.jpg)


The values ​​that were previously stated "'light' | 'dark' | 'auto'" should be added next to the size values?

**Comment by pigoz** [comment]
Thank you for testing. Which Anki plugin are you using for night mode?

As for AnkiDroid the behaviour is quite strange: is your config like this?
```
<script>
window.AnkiCanvasOptions = {
  frontCanvasSize: 300,
  frontLineWidth: 7,
  backCanvasSize: 150,
  backLineWidth: 3.5,
  colorScheme: 'auto',
}
</script>
```

**Comment by JhonnySalles** [comment]
This pluging
https://ankiweb.net/shared/info/1496166067

It's the same as you mentioned earlier.

**Comment by JhonnySalles** [comment]
It was missing the (colorScheme: 'auto',), but even adding nothing happened, 
the line is still black in front card.

I'll try to use a new user and get the _front.js script again

**Comment by pigoz** [comment]
Please, try to test this in isolation. Create a new user, and double click the deck I linked (_front.js is no longer needed since I found a way to embed the JavaScript directly in the card layout in version 0.4)

**Comment by JhonnySalles** [comment]
I actually tested it on a new user functioned. I do not know why, but I believe the anki is not overwriting the last type of card. When copying the code all the same worked perfectly and came with the new variable.

![2019_05_13_13 02 12](https://user-images.githubusercontent.com/43912638/57636707-044e1300-7580-11e9-99bd-29ea782f5ec3.jpg)

As for pc anki, I noticed a strange thing when performing the copy. I noticed that the card in edition gets to be black, but after saving it back to normal.

![Sem título2](https://user-images.githubusercontent.com/43912638/57636850-627af600-7580-11e9-906d-544159ab1535.jpg)
![Sem título3](https://user-images.githubusercontent.com/43912638/57636852-6444b980-7580-11e9-9795-435cd96a71ac.jpg)

Maybe it could be some rendering that the pc anki does differently, or else what turned black was your code at that time.

When saving the card, the ankidroid works normally, but on the pc it goes white again.

**Comment by JhonnySalles** [comment]
Thanks for all the effort, I believe that many others can enjoy this new update without burning their eyes at night kkkk

Perhaps an interesting point, if you like, could make the field colorScheme: 'auto' receive a hexadecial color, so you can have a greater customization in the trace. Just a tip.

Thank you so much for all the work.

**Comment by pigoz** [comment]
Sorry for the late reply. I suspect setting colorScheme to 'dark' in the AnkiOptions section of the card will solve the problem with desktop Anki.

As for hex customization, it's something I'm considering. But I'd like the user to be able to customize both light and dark mode, or even add user defined modes so that they can force some colors only on certain platforms.

**Comment by JhonnySalles** [comment]
oh yes, I understood.

**Comment by pigoz** [comment]
I published a new release: https://github.com/pigoz/anki-canvas/releases/tag/v0.5

Everything should be taken care of. Compared to what you tested, it's now possible to choose your own color, and I fixed the automatic color scheme selection when using desktop Anki.

**Comment by JhonnySalles** [comment]
wow, thx verry much.
