### ISSUE TITLE
Conflict with AnkiDroid’s gestures

### ISSUE THREAD

**Issue by rwmpelstilzchen** [pigoz/anki-canvas#6]
Hi,

Thanks for anki-canvas; it looks great :-)

If you enable AnkiDroid’s gestures feature gestures get triggered when you draw on the canvas. This breaks things completely. Is there any way to disable gestures within the canvas area?

Júda

**Comment by pigoz** [comment]
Hi Júda,

unfortunately, AFAIK that's not possible to control from anki-canvas which events are passed up to AnkiDroid. It was bothering me as well, and I ended up disabling gestures in AnkiDroid 😞
