### ISSUE TITLE
Disabling colors

### ISSUE THREAD

**Issue by nicolasmaia** [pigoz/anki-canvas#7]
Is it possible to disable the stroke colors on the back of the card?

**Comment by pigoz** [comment]
Not currently, but it can probably be added as an option fairly easily.

_Why_ do you want to disable them though? It's what allows you to check your stroke order, and the kanji reference image created by Anki uses colors anyway.

**Comment by nicolasmaia** [comment]
I just don't really mind the stroke order. 
But wait, are those images generated automatically?

**Comment by pigoz** [comment]
Yes, through this: https://ankiweb.net/shared/info/1964372878

**Comment by pigoz** [comment]
Sorry for the delay!

I have a new year present: https://github.com/pigoz/anki-canvas/releases/tag/v0.6

You can now use `backBrushColorizer: 'none'` as mentioned in the project [README](https://github.com/pigoz/anki-canvas#options).

If you find some issues, please reopen the issue!
